package SessionIndex;

# Pure module: reads one Claude Code session transcript (JSONL) and returns a
# structured entry describing who started it, when it started/was last
# active, its first/last typed message, and whether it is listable.
#
# Spec: .ccpraxis-local-data/blueprints/sandbox-session-ux/specs/02-session-index-spec.md
# Decision 20 fix round (reports/02-session-index-review.md M1-M3): the
# forward/backward scans are no longer capped at a fixed byte window --
# they widen in chunks until what they need is found, or the file is
# exhausted. Every line that is actually inspected is genuinely JSON-decoded
# at least for the top-level keys it needs; nothing is ever trusted from an
# unanchored regex match on raw bytes (that was the root cause of M1-M3).
#
# Contract: never dies, never warns, no console output, no writes, no
# spawning. Core modules only. Paths are handled as opaque byte strings.

use strict;
# Deliberately NOT `use warnings` -- the spec requires zero warnings on any
# input, including malformed/undef data paths that are awkward to prove
# warning-free under every lexical warnings category. Errors are still
# caught explicitly via eval() throughout.

use JSON::PP ();
use Time::Local ();

# ---------------------------------------------------------------------------
# Tunables (package variables; tests may `local`-ize them).
# ---------------------------------------------------------------------------
our $HEAD_MAX_BYTES = 512 * 1024;   # forward-scan chunk size
our $TAIL_MAX_BYTES = 512 * 1024;   # backward-scan chunk size
our $MAX_TEXT_CHARS = 4096;         # first_typed / last_typed truncation

my $DECODER = JSON::PP->new->utf8;

our $PREAMBLE_RE = qr/\A\s*You are (?:a|the) ccpraxis \*{0,2}(?:butler coordinator|resolve-judge|harvest-judge|escalation-resolver)\b/;

my @NOISE_PREFIXES = (
    '[Request interrupted',
    '<command-name>',
    '<command-message>',
    '<command-args>',
    '<command-stdout>',
    '<local-command-',
    '<task-notification>',
    '<system-reminder>',
    '<bash-input>',
    '<bash-stdout>',
    '<bash-stderr>',
    '<user-prompt-submit-hook>',
    'This session is being continued from a previous conversation',
    'Caveat: The messages below were generated by the user while running local commands',
);

# ---------------------------------------------------------------------------
# parse_ts($iso_string) -> $epoch_int | undef
# ---------------------------------------------------------------------------
sub parse_ts {
    my ($s) = @_;
    return undef unless defined $s;
    return undef unless $s =~ /\A(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(Z|[+-]\d{2}:\d{2})?\z/;
    my ($y, $mo, $d, $h, $mi, $se, $tz) = ($1, $2, $3, $4, $5, $6, $7);
    my $epoch = eval { Time::Local::timegm($se + 0, $mi + 0, $h + 0, $d + 0, $mo - 1, $y + 0) };
    return undef unless defined $epoch;
    if (defined $tz && $tz ne 'Z' && $tz =~ /\A([+-])(\d{2}):(\d{2})\z/) {
        my $sign = ($1 eq '+') ? 1 : -1;
        my $offset_sec = $sign * (($2 + 0) * 3600 + ($3 + 0) * 60);
        $epoch -= $offset_sec;
    }
    return $epoch;
}

# ---------------------------------------------------------------------------
# typed_text(\%record) -> $text | undef
#
# The reference implementation: operates on a fully-decoded record hashref.
# Used directly by callers that already have one (tests; the "first
# conversational record" path below, which needs several of its top-level
# fields anyway). The scanners further down reimplement the same rules
# against raw-line top-level spans (never a full recursive decode) purely
# for speed; _content_to_text() is the single shared source of truth for
# the content-extraction half of the rules so the two paths cannot diverge.
# ---------------------------------------------------------------------------
sub typed_text {
    my ($rec) = @_;
    return undef unless ref($rec) eq 'HASH';
    return undef unless defined($rec->{type}) && $rec->{type} eq 'user';

    for my $flag (qw(isSidechain isMeta isCompactSummary isVisibleInTranscriptOnly)) {
        return undef if exists($rec->{$flag}) && $rec->{$flag};
    }
    return undef if exists $rec->{toolUseResult};

    if (exists($rec->{promptSource}) && defined($rec->{promptSource}) && $rec->{promptSource} eq 'system') {
        return undef;
    }
    if (exists($rec->{origin}) && ref($rec->{origin}) eq 'HASH') {
        my $ok = $rec->{origin}{kind};
        return undef if defined($ok) && $ok ne 'human';
    }

    my $message = $rec->{message};
    my $content = (ref($message) eq 'HASH') ? $message->{content} : undef;
    return _content_to_text($content);
}

sub _content_to_text {
    my ($content) = @_;
    return undef unless defined $content;

    my $text;
    if (!ref($content)) {
        $text = $content;
    } elsif (ref($content) eq 'ARRAY') {
        for my $block (@$content) {
            next unless ref($block) eq 'HASH';
            if (defined($block->{type}) && $block->{type} eq 'tool_result') {
                return undef;
            }
        }
        my @textblocks;
        for my $block (@$content) {
            next unless ref($block) eq 'HASH';
            if (defined($block->{type}) && $block->{type} eq 'text' && defined($block->{text})) {
                push @textblocks, $block->{text};
            }
        }
        return undef unless @textblocks;
        $text = join("\n", @textblocks);
    } else {
        return undef;
    }

    return undef unless defined $text;
    my $trimmed = $text;
    $trimmed =~ s/\A\s+//;
    return undef if $trimmed eq '';

    for my $prefix (@NOISE_PREFIXES) {
        return undef if index($trimmed, $prefix) == 0;
    }

    return $text;
}

# ---------------------------------------------------------------------------
# Depth-1 (top-level keys only) span scanner.
#
# Review defects M1-M3 all trace back to using an unanchored regex against
# raw bytes to decide a record's timestamp/type/message: a nested key with
# the same name silently wins. The fix is to actually walk the object's
# top-level key/value pairs -- respecting string quoting/escaping and
# object/array nesting depth -- and hand back the byte SPAN of each
# top-level value, without recursively decoding anything nested inside it.
# JSON::PP is then used only on the (small) fragment a caller actually
# needs, so a multi-KB tool_result blob living inside "message" never gets
# parsed unless "message" itself is the fragment being decoded, and never
# at all when a cheaper top-level check (toolUseResult existing, type not
# being "user", ...) already rules the line out.
# ---------------------------------------------------------------------------
sub _skip_string {
    my ($line, $pos) = @_;   # $pos is the index of the opening '"'
    my $len = length($line);
    my $i = $pos + 1;
    while (1) {
        my $q = index($line, '"', $i);
        return $len if $q < 0;
        my $bs = 0;
        my $k = $q - 1;
        while ($k > $pos && substr($line, $k, 1) eq '\\') {
            $bs++;
            $k--;
        }
        return $q + 1 if ($bs % 2) == 0;
        $i = $q + 1;
    }
}

sub _skip_balanced {
    my ($line, $pos, $open, $close) = @_;
    my $len = length($line);
    my $depth = 0;
    my $i = $pos;
    while ($i < $len) {
        my $c = substr($line, $i, 1);
        if ($c eq '"') { $i = _skip_string($line, $i); next; }
        if ($c eq $open) { $depth++; $i++; next; }
        if ($c eq $close) {
            $depth--;
            $i++;
            return $i if $depth == 0;
            next;
        }
        $i++;
    }
    return $len;
}

# Returns \%spans (key => [value_start, value_end)) for every top-level key
# in $line, or undef if $line doesn't parse as a JSON object at all.
sub _scan_top_level {
    my ($line) = @_;
    my $len = length($line);
    my $i = index($line, '{');
    return undef if $i < 0;
    $i++;
    my %spans;
    while ($i < $len) {
        while ($i < $len) {
            my $c = substr($line, $i, 1);
            last unless $c eq ' ' || $c eq "\t" || $c eq "\r" || $c eq "\n" || $c eq ',';
            $i++;
        }
        last if $i >= $len;
        my $c = substr($line, $i, 1);
        if ($c eq '}') { $i++; last; }
        return undef unless $c eq '"';
        my $key_start = $i;
        $i = _skip_string($line, $i);
        my $key = substr($line, $key_start + 1, $i - $key_start - 2);
        while ($i < $len && substr($line, $i, 1) =~ /[ \t\r\n]/) { $i++; }
        return undef unless $i < $len && substr($line, $i, 1) eq ':';
        $i++;
        while ($i < $len && substr($line, $i, 1) =~ /[ \t\r\n]/) { $i++; }
        return undef if $i >= $len;
        my $val_start = $i;
        my $vc = substr($line, $i, 1);
        if ($vc eq '{') { $i = _skip_balanced($line, $i, '{', '}'); }
        elsif ($vc eq '[') { $i = _skip_balanced($line, $i, '[', ']'); }
        elsif ($vc eq '"') { $i = _skip_string($line, $i); }
        else {
            while ($i < $len) {
                my $cc = substr($line, $i, 1);
                last if $cc eq ',' || $cc eq '}' || $cc eq ' ' || $cc eq "\t" || $cc eq "\r" || $cc eq "\n";
                $i++;
            }
        }
        $spans{$key} = [$val_start, $i] unless exists $spans{$key};
    }
    return \%spans;
}

sub _span_decode {
    my ($line, $spans, $key) = @_;
    my $sp = $spans->{$key} or return undef;
    my $frag = substr($line, $sp->[0], $sp->[1] - $sp->[0]);
    return eval { $DECODER->decode($frag) };
}

# A record's time is its top-level "timestamp", or (for file-history-
# snapshot without one) the nested snapshot.timestamp -- never any other
# nested "timestamp" (M2). Both come from a real decode of the relevant
# top-level fragment, never an unanchored raw match.
sub _top_level_time {
    my ($line, $spans, $type) = @_;
    if (exists $spans->{timestamp}) {
        my $t = parse_ts(_span_decode($line, $spans, 'timestamp'));
        return $t if defined $t;
    }
    if (defined($type) && $type eq 'file-history-snapshot' && exists $spans->{snapshot}) {
        my $snap = _span_decode($line, $spans, 'snapshot');
        if (ref($snap) eq 'HASH' && defined($snap->{timestamp})) {
            return parse_ts($snap->{timestamp});
        }
    }
    return undef;
}

# typed_text(), reimplemented against top-level spans instead of a fully
# decoded record: cheap flag/string fields are decoded individually (all
# tiny fragments); "message" -- the only field that can be large -- is
# decoded only once every cheaper top-level check has already passed, and
# never at all when a top-level toolUseResult key exists (guaranteed noise
# per 3.2, regardless of what a multi-KB tool_result blob inside "message"
# contains). $type must already be known to be exactly "user" by the
# caller (the M3(a) fix: gate on the record's own top-level type, not an
# unanchored "type":"user" substring that could belong to nested content).
sub _candidate_typed_text {
    my ($line, $spans) = @_;

    for my $flag (qw(isSidechain isMeta isCompactSummary isVisibleInTranscriptOnly)) {
        next unless exists $spans->{$flag};
        my $v = _span_decode($line, $spans, $flag);
        return undef if $v;
    }
    return undef if exists $spans->{toolUseResult};

    if (exists $spans->{promptSource}) {
        my $v = _span_decode($line, $spans, 'promptSource');
        return undef if defined($v) && $v eq 'system';
    }
    if (exists $spans->{origin}) {
        my $v = _span_decode($line, $spans, 'origin');
        if (ref($v) eq 'HASH') {
            my $k = $v->{kind};
            return undef if defined($k) && $k ne 'human';
        }
    }

    return undef unless exists $spans->{message};
    my $msg = _span_decode($line, $spans, 'message');
    return undef unless ref($msg) eq 'HASH';
    return _content_to_text($msg->{content});
}

# One line's worth of everything the scanners need, computed via the
# top-level-only span scan above. Returns undef for an undecodable line
# (malformed JSON, non-object) -- contributes nothing, per 3.4.
sub _probe_line {
    my ($line) = @_;
    my $spans = _scan_top_level($line);
    return undef unless $spans;
    my $type = _span_decode($line, $spans, 'type');
    $type = undef unless !ref($type);
    my $time = _top_level_time($line, $spans, $type);
    my $typed;
    $typed = _candidate_typed_text($line, $spans) if defined($type) && $type eq 'user';
    return { spans => $spans, type => $type, time => $time, typed => $typed };
}

# ---------------------------------------------------------------------------
# Unbounded, chunked line readers.
#
# Forward: buffers growing chunks from the start; yields each complete line
# ("\n"-terminated, or the final unterminated fragment at true EOF) as soon
# as its terminator is seen, however many chunks that took -- so a single
# line far larger than one chunk is still read whole rather than truncated.
#
# Backward: mirrors this from the end. It only ever hands back a line once
# both of its boundaries are certain: the right edge is always true EOF (or
# a "\n" already seen), and the left edge is a "\n" already seen in the
# buffer -- or true BOF. This is the M1 fix: a final line bigger than one
# tail chunk keeps pulling earlier chunks until its own start is found,
# instead of silently treating "no newline in this window" as "no data".
# ---------------------------------------------------------------------------
sub _forward_lines_iter {
    my ($path, $chunk_size) = @_;
    $chunk_size = 64 * 1024 if !defined($chunk_size) || $chunk_size < 1;
    my $fh;
    return undef unless open($fh, '<:raw', $path);
    my $buf = '';
    my $eof = 0;
    my $ateof = 0;   # true once a call has returned undef
    return {
        next => sub {
            while (1) {
                my $nl = index($buf, "\n");
                if ($nl >= 0) {
                    my $line = substr($buf, 0, $nl);
                    $buf = substr($buf, $nl + 1);
                    return $line;
                }
                if ($eof) {
                    if (length($buf)) {
                        my $line = $buf;
                        $buf = '';
                        return $line;
                    }
                    $ateof = 1;
                    return undef;
                }
                my $chunk;
                my $n = read($fh, $chunk, $chunk_size);
                if (!defined($n) || $n == 0) { $eof = 1; next; }
                $buf .= $chunk;
            }
        },
        at_eof => sub { return $ateof; },
    };
}

sub _backward_lines_iter {
    my ($path, $size, $chunk_size) = @_;
    $chunk_size = 64 * 1024 if !defined($chunk_size) || $chunk_size < 1;
    return undef unless defined($size) && $size >= 0;
    my $fh;
    return undef unless open($fh, '<:raw', $path);
    my $pos = $size;
    my $buf = '';
    my $bof = ($pos == 0) ? 1 : 0;
    return {
        next => sub {
            while (1) {
                my $nl = rindex($buf, "\n");
                if ($nl >= 0) {
                    my $line = substr($buf, $nl + 1);
                    $buf = substr($buf, 0, $nl);
                    return $line;
                }
                if ($bof) {
                    if (length($buf)) {
                        my $line = $buf;
                        $buf = '';
                        return $line;
                    }
                    return undef;
                }
                my $read_len = ($pos >= $chunk_size) ? $chunk_size : $pos;
                my $new_pos = $pos - $read_len;
                seek($fh, $new_pos, 0);
                my $chunk = '';
                read($fh, $chunk, $read_len);
                $buf = $chunk . $buf;
                $pos = $new_pos;
                $bof = 1 if $pos == 0;
            }
        },
    };
}

# ---------------------------------------------------------------------------
# Forward scan: widens until the first typed message AND the first
# timestamped record are both found, or the file is exhausted. Also
# resolves the first conversational record (for classification) and the
# very first decodable record's sessionId (for the id fallback) along the
# way -- both are only ever needed from whatever the file's first few
# records turn out to be, so they fall out of the same single pass.
# ---------------------------------------------------------------------------
sub _scan_forward {
    my ($path, $chunk_size) = @_;
    my $iter = _forward_lines_iter($path, $chunk_size);
    return undef unless $iter;

    my %r = (
        found_conv     => 0,
        conv_sidechain => undef,
        conv_entry     => undef,
        conv_prompt    => undef,
        conv_typed     => undef,
        first_session  => undef,
        started_at     => undef,
        first_typed    => undef,
        running_last   => undef,   # last timestamp seen so far, for the
                                    # "no typed message anywhere" shortcut
        reached_eof    => 0,
    );
    my $got_first_any = 0;

    while (1) {
        my $line = $iter->{next}->();
        if (!defined $line) { $r{reached_eof} = 1; last; }
        next unless length($line);

        my $p = _probe_line($line);
        next unless $p;

        if (!$got_first_any) {
            $got_first_any = 1;
            $r{first_session} = _span_decode($line, $p->{spans}, 'sessionId');
        }

        if (!$r{found_conv} && defined($p->{type}) && ($p->{type} eq 'user' || $p->{type} eq 'assistant')) {
            $r{found_conv}     = 1;
            $r{conv_sidechain} = _span_decode($line, $p->{spans}, 'isSidechain');
            $r{conv_entry}     = _span_decode($line, $p->{spans}, 'entrypoint');
            $r{conv_prompt}    = _span_decode($line, $p->{spans}, 'promptSource');
            $r{conv_typed}     = $p->{typed};
        }

        if (defined $p->{time}) {
            $r{started_at}   = $p->{time} unless defined $r{started_at};
            $r{running_last} = $p->{time};
        }
        $r{first_typed} = $p->{typed} if !defined($r{first_typed}) && defined($p->{typed});

        last if defined($r{first_typed}) && defined($r{started_at});
    }

    return \%r;
}

sub _scan_backward {
    my ($path, $size, $chunk_size) = @_;
    my $iter = _backward_lines_iter($path, $size, $chunk_size);
    return undef unless $iter;

    my ($last_active_at, $last_typed);
    while (1) {
        my $line = $iter->{next}->();
        last unless defined $line;
        next unless length($line);

        my $p = _probe_line($line);
        next unless $p;

        $last_active_at = $p->{time}  if !defined($last_active_at) && defined($p->{time});
        $last_typed     = $p->{typed} if !defined($last_typed)     && defined($p->{typed});

        last if defined($last_active_at) && defined($last_typed);
    }
    return ($last_active_at, $last_typed);
}

sub _classify {
    my ($found, $is_sidechain, $entrypoint, $promptSource, $typed) = @_;
    return ('human', 'default') unless $found;

    return ('sidechain', 'metadata') if $is_sidechain;

    my $has_entrypoint   = defined($entrypoint)   && length($entrypoint);
    my $has_promptSource = defined($promptSource) && length($promptSource);

    if (($has_entrypoint && $entrypoint =~ /\Asdk-/) || ($has_promptSource && $promptSource eq 'sdk')) {
        return (defined($typed) && $typed =~ $PREAMBLE_RE) ? ('coordinator', 'metadata') : ('headless', 'metadata');
    }

    if ($has_entrypoint) {
        return ('human', 'metadata');
    }

    if (!$has_promptSource) {
        return (defined($typed) && $typed =~ $PREAMBLE_RE) ? ('coordinator', 'preamble') : ('human', 'default');
    }

    # promptSource present (non-sdk) but no entrypoint (e.g. "typed"): human,
    # decided from metadata.
    return ('human', 'metadata');
}

sub _trunc_text {
    my ($t) = @_;
    return $t unless defined $t;
    return $t if length($t) <= $MAX_TEXT_CHARS;
    return substr($t, 0, $MAX_TEXT_CHARS);
}

# ---------------------------------------------------------------------------
# index_file($path) -> \%entry | undef
# ---------------------------------------------------------------------------
sub index_file {
    my ($path) = @_;
    return undef unless defined($path) && length($path);
    return undef unless -f $path && -r $path;

    my @st = stat($path);
    return undef unless @st;
    my $mtime = $st[9];
    my $size  = $st[7];
    $size = 0 unless defined $size;

    my $fwd = eval { _scan_forward($path, $HEAD_MAX_BYTES) };
    return undef unless $fwd;

    my ($last_active_at, $last_typed);
    if ($fwd->{reached_eof} && !defined($fwd->{first_typed})) {
        # Forward already read the whole file looking for a typed message
        # and found none -- 3.4's "a file with no typed message is read
        # fully once": reuse what forward already saw instead of reading
        # the whole file again backward.
        $last_active_at = $fwd->{running_last};
        $last_typed     = undef;
    } else {
        my $ok = eval {
            ($last_active_at, $last_typed) = _scan_backward($path, $size, $TAIL_MAX_BYTES);
            1;
        };
        ($last_active_at, $last_typed) = (undef, undef) unless $ok;
    }

    my $started_at  = $fwd->{started_at};
    my $first_typed = $fwd->{first_typed};

    my $time_source;
    if (!defined($started_at) && !defined($last_active_at)) {
        $started_at     = $mtime;
        $last_active_at = $mtime;
        $time_source    = 'mtime';
    } else {
        $time_source = 'records';
        $started_at     = $last_active_at unless defined $started_at;
        $last_active_at = $started_at     unless defined $last_active_at;
    }

    # id: filename stem if UUID-shaped, else the first record's sessionId.
    my $id;
    my $basename = $path;
    $basename =~ s{.*[/\\]}{};
    my $stem = $basename;
    $stem =~ s/\.jsonl\z//i;
    if (length($stem) && $stem =~ /\A[0-9a-fA-F-]{8,}\z/) {
        $id = $stem;
    } elsif (defined($fwd->{first_session})) {
        $id = $fwd->{first_session};
    } else {
        $id = undef;
    }

    my ($kind, $classified_by) = _classify(
        $fwd->{found_conv}, $fwd->{conv_sidechain}, $fwd->{conv_entry}, $fwd->{conv_prompt}, $fwd->{conv_typed},
    );
    my $human = ($kind eq 'human') ? 1 : 0;
    my $empty = (!defined($first_typed) && !defined($last_typed)) ? 1 : 0;
    my $listable = ($human && !$empty) ? 1 : 0;

    my $same_message;
    if ($empty) {
        $same_message = 0;
    } elsif (!defined($first_typed) || !defined($last_typed)) {
        $same_message = 1;
    } else {
        $same_message = ($first_typed eq $last_typed) ? 1 : 0;
    }

    my $truncated = ($size > $HEAD_MAX_BYTES + $TAIL_MAX_BYTES) ? 1 : 0;

    return {
        id             => $id,
        path           => $path,
        mtime          => $mtime,
        size           => $size,
        kind           => $kind,
        human          => $human,
        classified_by  => $classified_by,
        started_at     => $started_at,
        last_active_at => $last_active_at,
        time_source    => $time_source,
        first_typed    => _trunc_text($first_typed),
        last_typed     => _trunc_text($last_typed),
        same_message   => $same_message,
        empty          => $empty,
        listable       => $listable,
        truncated      => $truncated,
    };
}

# ---------------------------------------------------------------------------
# index_dir($dir) -> \@entries
# ---------------------------------------------------------------------------
sub index_dir {
    my ($dir) = @_;
    return [] unless defined($dir) && length($dir);
    return [] unless -d $dir && -r $dir;

    my @names;
    my $ok = eval {
        opendir(my $dh, $dir) or die "opendir: $!";
        @names = readdir($dh);
        closedir($dh);
        1;
    };
    return [] unless $ok;

    my @entries;
    for my $name (@names) {
        next unless defined($name) && $name =~ /\.jsonl\z/i;
        my $full = "$dir/$name";
        next unless -f $full;
        my $entry = index_file($full);
        next unless defined $entry;
        next unless defined $entry->{id};
        push @entries, $entry;
    }

    @entries = sort {
        $b->{last_active_at} <=> $a->{last_active_at}
            or
        $a->{id} cmp $b->{id}
    } @entries;

    return \@entries;
}

1;
